### ISSUE TITLE
Why deploy services to different namespaces by using helm?

### ISSUE THREAD

**Issue by frezes** [OpenFunction/charts#4]
Why deploy services to different namespaces by using helm?  Maybe we can use ofn-xxx-xxx instead, like ofn-knative-controller.

**Comment by wrongerror** [comment]
We have discussed this issue in https://github.com/OpenFunction/OpenFunction/issues/271.
I think it is clearer for dependent components to use their own namespace, so that when the user encounters a problem with a component, the component's own documentation is adapted when debugging
